sudo: required
language: bash

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: $EB_REGION
  app: $EB_APP_NAME
  env: $EB_ENV_NAME
  bucket_name: $BUCKET_NAME
  bucket_path: $BUCKET_PATH
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
