version: '3'
services:
  frontendapp:
    image: souravmondal10/frontend
    container_name: php-frontend-app
    restart: always
    working_dir: /var/www/html
  datastore:
    image: souravmondal10/datastore
    container_name: php-data-store
    restart: always
    working_dir: /var/www/html
  api:
    image: souravmondal10/api
    container_name: api
    restart: always
    working_dir: /var/www/html
  nginxroute:
    image: souravmondal10/nginxroute
    container_name: nginxroute
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - frontendapp
