version: '3'
services:
  frontendapp:
    build:
      context: ../frontEnd
      dockerfile: Dockerfile
    container_name: php-frontend-app
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
  datastore:
    build:
      context: ../dataStore
      dockerfile: Dockerfile
    container_name: php-data-store
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../api:/var/www/html
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password_xxx
      MYSQL_DATABASE: mysql_database_xxx
    volumes:
      - ../mysql-data:/var/lib/mysql/
      - ./mysql_fixtures/fixture.sql:/docker-entrypoint-initdb.d/dump.sql
  redis:
    image: redis
    container_name: redis
    restart: always
  tests:
    build:
      context: ../tests
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
      - datastore
