version: '3'
services:
  frontendapp:
    image: souravmondal10/frontend
    container_name: php-frontend-app
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
  datastore:
    image: souravmondal10/datastore
    container_name: php-data-store
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
  api:
    image: souravmondal10/api
    container_name: api
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
  nginxroute:
    image: souravmondal10/nginxroute
    container_name: nginxroute
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - frontendapp
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: very_strong_password
      MYSQL_DATABASE: UserBase
    volumes:
      - ../mysql-data:/var/lib/mysql/
      - ./mysql_fixtures/fixture.sql:/docker-entrypoint-initdb.d/dump.sql
  redis:
    image: redis
    container_name: redis
    restart: always
  tests:
    image: souravmondal10/tests
    container_name: tests
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
      - datastore
