version: '3'

services:
  frontendapp:
    build:
      context: ../frontEnd
      dockerfile: Dockerfile
    container_name: php-frontend-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../frontEnd:/var/www/html
  frontendnginx:
    image: nginx:1.19-alpine
    container_name: frontend-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../frontEnd:/var/www/html
      - ./nginx:/etc/nginx/conf.d
  datastore:
    build:
      context: ../dataStore
      dockerfile: Dockerfile
    container_name: php-data-store
    restart: always
    working_dir: /var/www/html
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../api:/var/www/html
  apinginx:
    image: nginx:1.19-alpine
    container_name: api-nginx
    restart: always
    ports:
      - 8081:80
    volumes:
      - ../api:/var/www/html
      - ./apinginx:/etc/nginx/conf.d
  jenkins:
    image: jenkins:2.60.3
    ports:
      - 8080:8080
    container_name: jenkins
    restart: always
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: very_strong_password
      MYSQL_DATABASE: UserBase
    volumes:
      - ../mysql-data:/var/lib/mysql/
      - ./mysql_fixtures:/tmp/import_mysql_database
    ports:
      - 3306:3306
  redis:
    image: redis
    container_name: redis
    restart: always
