pipeline {
    agent any
    stages {
        stage('pull-infrastructure') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'sourav-github', url: 'git@github.com:souravmondal10/infrastructure.git']]])
                sh "mkdir -p git-pulls;cd git-pulls"
                git branch: 'master',
                    credentialsId: 'sourav-github',
                    url: 'git@github.com:souravmondal10/infrastructure.git'
                sh "ls -lat"
            }
        }
        stage('commit-changes') {
            steps {
                sshagent(credentials : ['sourav']) {
                    sh 'ssh -o StrictHostKeyChecking=no sourav@192.168.0.128 "pwd;ls -al"'
                    sh 'scp ./source/filename sourav@192.168.0.128:/home/sourav/'
                }
            }
        }
    }
}
